version: '3'

services:
    web:
        container_name: web
        build:
            context: php
        ports:
            - 8080:80
        volumes:
            - ./app/:/var/www/html
        restart: always
    mariadb:
        container_name: db
        image: mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=test
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpass
        ports:
            - 3307:3306
        links:
            - web
        depends_on:
            - web
        restart: always
